import type { Metadata } from 'next'
import { roboto } from './ui/fonts';
import './globals.css'
import Header from './components/header'
import Footer from './components/footer'

export const metadata: Metadata = {
  title: {
    absolute:"",
    default:"Next.js training by Iverson",
    template:"%s | Iverson Training"
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
